sonar.projectKey=NoTIPswe_notip-crypto-sdk
sonar.organization=notipswe

sonar.sources=src
sonar.exclusions=src/**/*.spec.ts, src/generated/**/*

sonar.tests=src,tests
sonar.test.inclusions=src/**/*.spec.ts,tests/**/*.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.testExecutionReportPaths=coverage/test-reporter.xml